services:
  hqplayer:
    image: hqplayer:5.14.0
    container_name: hqplayer
    network_mode: host
    dns:
      - 1.1.1.1
    volumes:
      - hqplayer-home:/var/lib/hqplayer/home
      - hqplayer-data:/etc/hqplayer
      - ./bin:/home
    restart: unless-stopped
    devices:
      - "/dev/snd:/dev/snd"
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
    security_opt:
      - seccomp:unconfined

volumes:
  hqplayer-home:
    name: hqplayer-home
  hqplayer-data:
    name: hqplayer-data
