services:
  hqplayer:
    image: hqplayer:5.7.0
    container_name: hqplayer
    network_mode: host
    volumes:
      - hqplayer-home:/var/lib/hqplayer/home
      - hqplayer-data:/etc/hqplayer
    restart: unless-stopped
    devices:
      - "/dev/snd:/dev/snd"
volumes:
  hqplayer-home:
    name: hqplayer-home
  hqplayer-data:
    name: hqplayer-data
